# sudo because we are going to use docker
sudo: required
services:
  - docker
before_install:
  # Add the encrypted service-account.json
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Install Google Cloud SDK CLI - SDK to communicate Google Cloud
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl in travis
  - gcloud components update kubectl
  # service account is like IAM user in AWS for travis (permissions for travis to access google cloud)
  - gcloud auth activate-service-account --key-file service-account.json
# Configure the SDK with out Google Cloud auth info

# Login to Docker CLI

# Build the 'test' version of multi-client

# Run tests

# If tests are successful, run a script to deploy newest images

# Build all our images, tag each one, push each to docker hub

# Apply all configs in the 'k8s' folder

# Imperatively set latest images on each deployment
